# Generated by Django 5.0.8 on 2024-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formcomunicate',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='formcomunicate',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Tu nombre'),
        ),
        migrations.AlterField(
            model_name='formcomunicate',
            name='opinion',
            field=models.TextField(max_length=500, verbose_name='Cuéntanos tu opinión'),
        ),
    ]
