# Generated by Django 5.0.8 on 2024-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_menu_imagen_alter_formcomunicate_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
